feat(sshpick): prettier UI

diff --git a/.local/bin/sshpick b/.local/bin/sshpick
--- a/.local/bin/sshpick
+++ b/.local/bin/sshpick
@@ -1,8 +1,19 @@
 #!/bin/bash
-USAGE="Usage: $0 [ --ip,-i <hostname> | --user,-u <hostname> | --help,-h ] [ <query> ]"
+USAGE="Usage: $0 [ --help,-h | --ip,-i <hostname> | --user,-u <hostname> | --port,-p <hostname> ] [ <query> ]"
+YELLOW='\033[1;33m'
+LIGHT_BLUE='\033[1;34m'
+RED='\033[1;31m'
+NC='\033[0m' # No Color
 
 main() {
     local command="$1"
+    if [ "$command" == "--help" ] || [ "$command" == "-h" ]; then
+        echo "Utility to quickly retrieve SSH host information from ~/.ssh/config"
+        echo "$USAGE"
+        exit 0
+    fi
+
+    check_dependencies
     case "$command" in
         "--ip" | "-i")
             local host
@@ -14,10 +25,10 @@ main() {
             host="${2:-$(choose_host)}"
             get_host_user "$host"
             ;;
-        "-h" | "--help")
-            echo "Utility to quickly retrieve SSH host information from ~/.ssh/config."
-            echo "$USAGE"
-            exit 0
+        "--port" | "-p")
+            local host
+            host="${2:-$(choose_host)}"
+            get_host_port "$host"
             ;;
         "")
             choose_host
@@ -28,14 +39,32 @@ main() {
     esac
 }
 
+check_dependencies() {
+    local dependencies=(ssh awk fzf find)
+    for dep in "${dependencies[@]}"; do
+        check_dep "$dep"
+    done
+}
+
+check_dep() {
+    local dep="$1"
+    if ! command -v "$dep" &> /dev/null; then
+        log_error "$dep is not installed. Please install $dep to use this script"
+    fi
+}
+
 log_error() {
-    echo "ERROR: $*" >&2
+    echo -e "[${RED}ERROR${NC}] $*" >&2
     exit 1
 }
 
 choose_host() {
-    if ! command -v fzf &> /dev/null; then
-        log_error "fzf is not installed. Please install fzf to use this script."
+    mapfile -t ssh_config < <(
+        [ -f ~/.ssh/config ] && echo ~/.ssh/config
+        [ -d ~/.ssh/config.d ] && find ~/.ssh/config.d -type f
+    )
+    if [ ${#ssh_config[@]} -eq 0 ]; then
+        log_error "No SSH config files found in ~/.ssh/config or ~/.ssh/config.d/"
     fi
 
     local hosts
@@ -44,10 +73,10 @@ choose_host() {
             for (i=2; i<=NF; i++)
                 if ($i !~ /[*?]/ && $i != "*")
                     print $i
-        }' ~/.ssh/config ~/.ssh/config.d/* 2>/dev/null | sort -u)
+        }' "${ssh_config[@]}" 2>/dev/null | sort -u)
 
     if [ -z "$hosts" ]; then
-        log_error "No hosts found in ~/.ssh/config."
+        log_error "No hosts found in ~/.ssh/config"
     fi
 
     local query_flag
@@ -57,16 +86,27 @@ choose_host() {
         query_flag=()
     fi
 
+    local preview_awk_cmd
+    preview_awk_cmd=$(cat <<EOF
+    /^user / {print "User: " \$2}
+    /^hostname / {print "Hostname: " \$2}
+    /^port / {print "Port: " \$2}
+EOF
+    )
+
     local selected_host
     selected_host=$(
         echo "$hosts" | fzf \
+            --height=10 \
             --prompt="Select a host: " \
             "${query_flag[@]}" \
-            --preview="ssh -G {} 2>/dev/null | awk '/^hostname / {print \"IP: \" \$2} /^user / {print \"User: \" \$2} /^port / {print \"Port: \" \$2}'" \
-            --preview-window=up:3:wrap
+            --preview="ssh -G {} 2>/dev/null | awk '$preview_awk_cmd' | column -t" \
+            --preview-window=up:3 \
+            --preview-label="Host details" \
+            --preview-label-pos=+3
         )
     if [ -z "$selected_host" ]; then
-        log_error "No host selected."
+        log_error "No host selected"
     fi
 
     echo "$selected_host"
@@ -77,7 +117,7 @@ get_host_ip() {
     local ip
     ip=$(ssh -G "$host" | awk '/^hostname / {print $2}')
     if [ -z "$ip" ]; then
-        log_error "Could not retrieve IP for host '$host'."
+        log_error "Could not retrieve IP for host '$host'"
     fi
     echo "$ip"
 }
@@ -87,9 +127,19 @@ get_host_user() {
     local user
     user=$(ssh -G "$host" | awk '/^user / {print $2}')
     if [ -z "$user" ]; then
-        log_error "Could not retrieve user for host '$host'."
+        log_error "Could not retrieve user for host '$host'"
     fi
     echo "$user"
+}
+
+get_host_port() {
+    local host="$1"
+    local port
+    port=$(ssh -G "$host" | awk '/^port / {print $2}')
+    if [ -z "$port" ]; then
+        log_error "Could not retrieve port for host '$host'"
+    fi
+    echo "$port"
 }
 
 main "$@"
